### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by chrisangel666** [Pikurrot/whisper-gui#23]
Hi, master, What version of python is yours?

**Comment by Pikurrot** [comment]
The python version is **3.10.13**, it's defined in [configs/environment_cpu.yml](https://github.com/Pikurrot/whisper-gui/blob/2a9951f84f27de9959c1305f8c61d316ef9b5d85/configs/environment_cpu.yml), the installer already takes care of installing the correct version.
I use 3.10 rather than new ones for compatibility reasons.

**Comment by chrisangel666** [comment]
OK, THX

**Comment by chrisangel666** [comment]
Hi, master. Since I have upgraded to the new version, this error message has appeared. What's going on?
![er-1](https://github.com/user-attachments/assets/54b3116e-e9f1-477a-971f-28e7d1bbad12)
![er-2](https://github.com/user-attachments/assets/177c1ca5-d7a9-41ff-a5f8-bcaede33473d)

**Comment by chrisangel666** [comment]
OK, Thx
