### ISSUE TITLE
The demo example says people are 3D objects that's not really true it's at least four dimensional

### ISSUE THREAD

**Issue by crowlogic** [Pikurrot/whisper-gui#28]
You can't really project yourself due to the no cloning theorem as well 😎 cool project though

**Comment by Pikurrot** [comment]
Hi thanks for trying this program and good observation. You are right that we are 4D if we consider time. However I don't think the no-cloning theorem really applies here because it deals with identical copies of quantum states, but some higher dimensional being could somehow project itself to our known dimensions, similar to how our projection into a shadow is not a perfect copy of ourselves.
